# Single FRB

In [58]:
# imports
import pandas

from frb import frb
from frb.galaxies import frbgalaxy

# Let's do an FRB table first

## Load the full table

In [6]:
frbs_tbl, tbl_units = frb.build_table_of_frbs()

In [7]:
frbs_tbl

,FRB,RA,DEC,DM,DM_err,fluence,fluence_err,RM,RM_err,lpol,lpol_err,z,DMISM
0,FRB121102,82.994583,33.147917,558.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.19273,158.237866
1,FRB180916,29.503126,65.716754,348.760,0.100,NaN,NaN,NaN,NaN,NaN,NaN,0.03370,171.676368
2,FRB180924,326.105229,-40.900028,362.160,0.010,16.0,1.0,22.0,2.0,80.0,10.0,0.32120,41.894194
3,FRB181112,327.348458,-52.970925,589.270,0.030,NaN,NaN,10.9,0.9,NaN,NaN,0.47550,42.395814
4,FRB190102,322.415667,-79.475694,364.545,0.004,14.0,1.0,-105.0,1.0,NaN,NaN,0.29120,56.815580
5,FRB190523,207.065000,72.469722,760.800,0.600,280.0,NaN,NaN,NaN,NaN,NaN,0.66000,36.798257
6,FRB190608,334.019875,-7.898250,339.800,1.000,NaN,NaN,NaN,NaN,NaN,NaN,0.11778,38.063404
7,FRB190611,320.745458,-79.397583,332.630,0.040,NaN,NaN,20.0,4.0,NaN,NaN,0.37780,57.195211
8,FRB190613,65.075520,73.706740,959.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.533333
9,FRB190614,65.075520,73.706740,959.000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.533333
10,FRB190711,329.419500,-80.358000,587.900,1.000,NaN,NaN,9.0,2.0,NaN,NaN,0.52172,55.930581
11,FRB190714,183.979667,-13.021028,504.130,0.100,NaN,NaN,NaN,NaN,NaN,NaN,0.23400,37.983046
12,FRB191001,323.351552,-54.747619,507.400,1.000,NaN,NaN,NaN,NaN,NaN,NaN,0.23400,44.703274
13,FRB191228,344.430292,-29.593847,298.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.881102
14,FRB200430,229.706417,12.376889,380.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.16100,27.019500

In [4]:
tbl_units

{'FRB': None,
 'RA': 'deg',
 'DEC': 'deg',
 'DM': 'pc / cm3',
 'DM_err': 'pc / cm3',
 'fluence': 'Jy ms',
 'fluence_err': 'Jy ms',
 'RM': 'rad / m2',
 'RM_err': 'rad / m2',
 'lpol': None,
 'lpol_err': None,
 'z': None,
 'DMISM': 'pc / cm3'}

## Setup

In [62]:
frb_properties = dict(DM='DM_FRB', DMISM='DM_ISM', RM='RM_FRB')

## Generate a new, single FRB table

In [63]:
frb_idx = 2  # FRB 180924

## Quantity, to get us rolling

In [64]:
frb_prop = [item for key,item in frb_properties.items()]
frb_prop

['DM_FRB', 'DM_ISM', 'RM_FRB']

In [14]:
frb_tbl = pandas.DataFrame(dict(Quantity=frb_prop))

In [15]:
frb_tbl

  Quantity
0   DM_FRB
1   DM_ISM
2   RM_FRB

In [44]:
hasattr(frbs_tbl.iloc[frb_idx], 'RM_err')

True

## Values and Error and Units

In [45]:
formats = dict(DM='.1f', DMISM='.1f', RM='.1f')

In [65]:
values, errors, units = [], [], []
for key in frb_properties.keys():
    value = frbs_tbl.iloc[frb_idx][key]
    if key in formats.keys():
        values.append(format(value, formats[key]))
    else:
        raise IOError("You must add a format for {}!".format(key))
    # Error?
    if hasattr(frbs_tbl.iloc[frb_idx], key+'_err'):
        error = frbs_tbl.iloc[frb_idx][key+'_err']
        errors.append(format(error, formats[key]))
    else:
        errors.append('--')
    # Unit
    units.append(tbl_units[key])

In [66]:
values, errors, units

(['362.2', '41.9', '22.0'],
 ['0.0', '--', '2.0'],
 ['pc / cm3', 'pc / cm3', 'rad / m2'])

In [67]:
frb_tbl['Measured Value'] = values
frb_tbl['Measured Error'] = errors
frb_tbl['Units'] = units

In [68]:
frb_tbl

  Quantity Measured Value Measured Error     Units
0   DM_FRB          362.2            0.0  pc / cm3
1   DM_ISM           41.9             --  pc / cm3
2   RM_FRB           22.0            2.0  rad / m2

## HTML

In [69]:
frb_tbl.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Quantity</th>\n      <th>Measured Value</th>\n      <th>Measured Error</th>\n      <th>Units</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>DM_FRB</td>\n      <td>362.2</td>\n      <td>0.0</td>\n      <td>pc / cm3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DM_ISM</td>\n      <td>41.9</td>\n      <td>--</td>\n      <td>pc / cm3</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>RM_FRB</td>\n      <td>22.0</td>\n      <td>2.0</td>\n      <td>rad / m2</td>\n    </tr>\n  </tbody>\n</table>'

# How about a quick Host?

In [86]:
hosts_tbl, host_tbl_units = frbgalaxy.build_table_of_hosts()

In [87]:
hosts_tbl

,Host,FRB,RA_host,DEC_host,AV_nebular,EBV_photom,EBV_photom_err,EBV_spec,Lnu_r,Lnu_r_err,...,Hgamma,Hgamma_err,[NII] 6584,[NII] 6584_err,[OIII] 5007,[OIII] 5007_err,[OII] 3726,[OII] 3726_err,[OII] 3729,[OII] 3729_err
0,HG121102,FRB121102,82.994508,33.147998,NaN,0.120534,0.008314,NaN,1.320299e+20,9.700207e+18,...,NaN,NaN,1.192102e-17,-9.990000e+02,4.380421e-16,8.379936e-18,NaN,NaN,NaN,NaN
1,HG180924,FRB180924,326.105208,-40.900225,0.791758,0.306803,0.110993,0.172170,9.181236e+21,4.590618e+20,...,3.529572e-17,1.893642e-18,1.943620e-16,2.883754e-18,7.872197e-17,1.866043e-18,3.977910e-17,2.348287e-18,6.947412e-17,2.507810e-18
2,HG181112,FRB181112,327.348583,-52.970911,0.000000,0.181903,0.095498,0.672897,6.294762e+21,4.280439e+20,...,7.177895e-18,2.126869e-18,4.894002e-17,1.035911e-17,5.406020e-17,3.254570e-18,NaN,NaN,NaN,NaN
3,HG190102,FRB190102,322.415000,-79.475667,0.094225,0.200533,0.096346,0.609513,3.810183e+21,2.021937e+20,...,1.073073e-16,2.017522e-17,1.686398e-16,1.874772e-17,3.795495e-16,2.659510e-17,3.201370e-16,2.804933e-17,4.209247e-16,2.971658e-17
4,HG190523,FRB190523,207.064330,72.470756,NaN,0.298632,0.154398,NaN,2.919162e+22,3.185671e+21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,HG190608,FRB190608,334.020417,-7.898889,0.375270,0.121315,0.013008,0.000000,1.344827e+22,6.724136e+20,...,3.924686e-16,3.359845e-17,1.831878e-15,3.824482e-17,1.495146e-15,4.441160e-17,1.214940e-15,7.397708e-17,1.942295e-15,7.851035e-17
6,HG190611,FRB190611,320.742821,-79.397247,1.050444,NaN,NaN,0.322490,NaN,NaN,...,NaN,NaN,1.225919e-17,3.543131e-18,1.769158e-17,4.187042e-18,NaN,NaN,NaN,NaN
7,HG190711,FRB190711,329.419167,-80.358125,NaN,0.186900,0.110826,NaN,1.755684e+21,1.263152e+20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HG190714,FRB190714,183.979559,-13.021112,0.893738,0.795107,0.094823,0.767906,4.045281e+21,2.022641e+20,...,NaN,NaN,1.695609e-16,2.762577e-18,3.061832e-17,2.856038e-18,NaN,NaN,NaN,NaN
9,HG191001,FRB191001,323.351851,-54.748515,1.722882,0.265424,0.164811,0.000000,3.114354e+22,1.557177e+21,...,1.494364e-17,4.295724e-17,1.390852e-15,1.946530e-17,3.617731e-16,3.458110e-17,NaN,NaN,NaN,NaN
10,HG200430,FRB200430,229.706333,12.376611,NaN,0.309596,0.198049,NaN,7.275365e+20,3.637682e+19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
list(hosts_tbl.keys())

['Host',
 'FRB',
 'RA_host',
 'DEC_host',
 'AV_nebular',
 'EBV_photom',
 'EBV_photom_err',
 'EBV_spec',
 'Lnu_r',
 'Lnu_r_err',
 'M_r',
 'M_r_err',
 'Mstar',
 'Mstar_err',
 'Mstar_spec',
 'SFR_nebular',
 'SFR_nebular_err',
 'SFR_photom',
 'SFR_photom_err',
 'Z_photom',
 'Z_photom_err',
 'Z_spec',
 'Z_spec_err',
 'age_mass',
 'f_AGN',
 'f_AGN_err',
 'u-r',
 'u-r_err',
 'DES_Y',
 'DES_Y_err',
 'DES_g',
 'DES_g_err',
 'DES_i',
 'DES_i_err',
 'DES_r',
 'DES_r_err',
 'DES_z',
 'DES_z_err',
 'EBV',
 'GMOS_N_g',
 'GMOS_N_g_err',
 'GMOS_N_i',
 'GMOS_N_i_err',
 'GMOS_N_r',
 'GMOS_N_r_err',
 'GMOS_N_z',
 'GMOS_N_z_err',
 'GMOS_S_g',
 'GMOS_S_g_err',
 'GMOS_S_i',
 'GMOS_S_i_err',
 'GMOS_S_r',
 'GMOS_S_r_err',
 'Pan-STARRS_g',
 'Pan-STARRS_g_err',
 'Pan-STARRS_i',
 'Pan-STARRS_i_err',
 'Pan-STARRS_r',
 'Pan-STARRS_r_err',
 'Pan-STARRS_y',
 'Pan-STARRS_y_err',
 'Pan-STARRS_z',
 'Pan-STARRS_z_err',
 'SDSS_g',
 'SDSS_g_err',
 'SDSS_i',
 'SDSS_i_err',
 'SDSS_r',
 'SDSS_r_err',
 'SDSS_u',
 'SDSS_u_err',
 'SDSS_z',
 'SDSS_z_err',
 'Spitzer_3.6',
 'Spitzer_3.6_err',
 'Spitzer_4.5',
 'Spitzer_4.5_err',
 'VISTA_H',
 'VISTA_H_err',
 'VISTA_J',
 'VISTA_J_err',
 'VISTA_Ks',
 'VISTA_Ks_err',
 'VISTA_Y',
 'VISTA_Y_err',
 'VLT_FORS2_I',
 'VLT_FORS2_I_err',
 'VLT_FORS2_g',
 'VLT_FORS2_g_err',
 'VLT_FORS2_u',
 'VLT_FORS2_u_err',
 'VLT_FORS2_z',
 'VLT_FORS2_z_err',
 'WFC3_F110W',
 'WFC3_F110W_err',
 'WFC3_F160W',
 'WFC3_F160W_err',
 'WISE_W1',
 'WISE_W1_err',
 'WISE_W2',
 'WISE_W2_err',
 'WISE_W3',
 'WISE_W3_err',
 'WISE_W4',
 'WISE_W4_err',
 'Halpha',
 'Halpha_err',
 'Hbeta',
 'Hbeta_err',
 'Hgamma',
 'Hgamma_err',
 '[NII] 6584',
 '[NII] 6584_err',
 '[OIII] 5007',
 '[OIII] 5007_err',
 '[OII] 3726',
 '[OII] 3726_err',
 '[OII] 3729',
 '[OII] 3729_err']

In [88]:
host_tbl_units

{'RA_host': 'deg',
 'DEC_host': 'deg',
 'AV_nebular': 'See galaxies.defs.py',
 'EBV_photom': 'See galaxies.defs.py',
 'EBV_photom_err': 'See galaxies.defs.py',
 'EBV_spec': 'See galaxies.defs.py',
 'Lnu_r': 'See galaxies.defs.py',
 'Lnu_r_err': 'See galaxies.defs.py',
 'M_r': 'See galaxies.defs.py',
 'M_r_err': 'See galaxies.defs.py',
 'Mstar': 'See galaxies.defs.py',
 'Mstar_err': 'See galaxies.defs.py',
 'Mstar_spec': 'See galaxies.defs.py',
 'SFR_nebular': 'See galaxies.defs.py',
 'SFR_nebular_err': 'See galaxies.defs.py',
 'SFR_photom': 'See galaxies.defs.py',
 'SFR_photom_err': 'See galaxies.defs.py',
 'Z_photom': 'See galaxies.defs.py',
 'Z_photom_err': 'See galaxies.defs.py',
 'Z_spec': 'See galaxies.defs.py',
 'Z_spec_err': 'See galaxies.defs.py',
 'age_mass': 'See galaxies.defs.py',
 'f_AGN': 'See galaxies.defs.py',
 'f_AGN_err': 'See galaxies.defs.py',
 'u-r': 'See galaxies.defs.py',
 'u-r_err': 'See galaxies.defs.py',
 'DES_Y': 'See galaxies.defs.py',
 'DES_Y_err': 'See galaxies.defs.py',
 'DES_g': 'See galaxies.defs.py',
 'DES_g_err': 'See galaxies.defs.py',
 'DES_i': 'See galaxies.defs.py',
 'DES_i_err': 'See galaxies.defs.py',
 'DES_r': 'See galaxies.defs.py',
 'DES_r_err': 'See galaxies.defs.py',
 'DES_z': 'See galaxies.defs.py',
 'DES_z_err': 'See galaxies.defs.py',
 'EBV': 'See galaxies.defs.py',
 'GMOS_N_g': 'See galaxies.defs.py',
 'GMOS_N_g_err': 'See galaxies.defs.py',
 'GMOS_N_i': 'See galaxies.defs.py',
 'GMOS_N_i_err': 'See galaxies.defs.py',
 'GMOS_N_r': 'See galaxies.defs.py',
 'GMOS_N_r_err': 'See galaxies.defs.py',
 'GMOS_N_z': 'See galaxies.defs.py',
 'GMOS_N_z_err': 'See galaxies.defs.py',
 'GMOS_S_g': 'See galaxies.defs.py',
 'GMOS_S_g_err': 'See galaxies.defs.py',
 'GMOS_S_i': 'See galaxies.defs.py',
 'GMOS_S_i_err': 'See galaxies.defs.py',
 'GMOS_S_r': 'See galaxies.defs.py',
 'GMOS_S_r_err': 'See galaxies.defs.py',
 'Pan-STARRS_g': 'See galaxies.defs.py',
 'Pan-STARRS_g_err': 'See galaxies.defs.py',
 'Pan-STARRS_i': 'See galaxies.defs.py',
 'Pan-STARRS_i_err': 'See galaxies.defs.py',
 'Pan-STARRS_r': 'See galaxies.defs.py',
 'Pan-STARRS_r_err': 'See galaxies.defs.py',
 'Pan-STARRS_y': 'See galaxies.defs.py',
 'Pan-STARRS_y_err': 'See galaxies.defs.py',
 'Pan-STARRS_z': 'See galaxies.defs.py',
 'Pan-STARRS_z_err': 'See galaxies.defs.py',
 'SDSS_g': 'See galaxies.defs.py',
 'SDSS_g_err': 'See galaxies.defs.py',
 'SDSS_i': 'See galaxies.defs.py',
 'SDSS_i_err': 'See galaxies.defs.py',
 'SDSS_r': 'See galaxies.defs.py',
 'SDSS_r_err': 'See galaxies.defs.py',
 'SDSS_u': 'See galaxies.defs.py',
 'SDSS_u_err': 'See galaxies.defs.py',
 'SDSS_z': 'See galaxies.defs.py',
 'SDSS_z_err': 'See galaxies.defs.py',
 'Spitzer_3.6': 'See galaxies.defs.py',
 'Spitzer_3.6_err': 'See galaxies.defs.py',
 'Spitzer_4.5': 'See galaxies.defs.py',
 'Spitzer_4.5_err': 'See galaxies.defs.py',
 'VISTA_H': 'See galaxies.defs.py',
 'VISTA_H_err': 'See galaxies.defs.py',
 'VISTA_J': 'See galaxies.defs.py',
 'VISTA_J_err': 'See galaxies.defs.py',
 'VISTA_Ks': 'See galaxies.defs.py',
 'VISTA_Ks_err': 'See galaxies.defs.py',
 'VISTA_Y': 'See galaxies.defs.py',
 'VISTA_Y_err': 'See galaxies.defs.py',
 'VLT_FORS2_I': 'See galaxies.defs.py',
 'VLT_FORS2_I_err': 'See galaxies.defs.py',
 'VLT_FORS2_g': 'See galaxies.defs.py',
 'VLT_FORS2_g_err': 'See galaxies.defs.py',
 'VLT_FORS2_u': 'See galaxies.defs.py',
 'VLT_FORS2_u_err': 'See galaxies.defs.py',
 'VLT_FORS2_z': 'See galaxies.defs.py',
 'VLT_FORS2_z_err': 'See galaxies.defs.py',
 'WFC3_F110W': 'See galaxies.defs.py',
 'WFC3_F110W_err': 'See galaxies.defs.py',
 'WFC3_F160W': 'See galaxies.defs.py',
 'WFC3_F160W_err': 'See galaxies.defs.py',
 'WISE_W1': 'See galaxies.defs.py',
 'WISE_W1_err': 'See galaxies.defs.py',
 'WISE_W2': 'See galaxies.defs.py',
 'WISE_W2_err': 'See galaxies.defs.py',
 'WISE_W3': 'See galaxies.defs.py',
 'WISE_W3_err': 'See galaxies.defs.py',
 'WISE_W4': 'See galaxies.defs.py',
 'WISE_W4_err': 'See galaxies.defs.py',
 'Halpha': 'See galaxies.defs.py',
 'Halpha_err': 'See galaxies.defs.py',
 'Hbeta': 'See galaxies.defs.py',
 'Hbeta_err': 'See galaxies.defs.py',
 'Hgamma': 'See galaxies.defs.py',
 'Hgamma_err': 'See galaxies.defs.py',
 '[NII] 6584': 'See galaxies.defs.py',
 '[NII] 6584_err': 'See galaxies.defs.py',
 '[OIII] 5007': 'See galaxies.defs.py',
 '[OIII] 5007_err': 'See galaxies.defs.py',
 '[OII] 3726': 'See galaxies.defs.py',
 '[OII] 3726_err': 'See galaxies.defs.py',
 '[OII] 3729': 'See galaxies.defs.py',
 '[OII] 3729_err': 'See galaxies.defs.py'}

In [61]:
idx_host = 1 # HG180924

In [71]:
host_properties = dict(Mstar='Stellar Mass', M_r='Absolute r-band mag.')

In [72]:
host_prop = [item for key,item in host_properties.items()]

In [84]:
host_formats = dict(Mstar='0.1f', M_r='0.2f')
host_scale = dict(Mstar=1e8, M_r=1.)
host_units = dict(Mstar='mag', M_r='mag')

## Start it

In [76]:
host_tbl = pandas.DataFrame(dict(Quantity=host_prop))

In [89]:
values, errors, units = [], [], []
for key in host_properties.keys():
    value = hosts_tbl.iloc[idx_host][key]
    if key in host_formats.keys():
        values.append(format(value/host_scale[key], host_formats[key]))
    else:
        raise IOError("You must add a format for {}!".format(key))
    # Error?
    if hasattr(hosts_tbl.iloc[idx_host], key+'_err'):
        error = hosts_tbl.iloc[idx_host][key+'_err']
        errors.append(format(error/host_scale[key], host_formats[key]))
    else:
        errors.append('--')
    # Unit
    if key in host_units.keys():
        units.append(host_units[key])
    else:
        units.append(host_tbl_units[key])

In [90]:
values, errors, units

(['132.3', '-20.81'], ['50.6', '0.05'], ['mag', 'mag'])

In [91]:
host_tbl['Measured Value'] = values
host_tbl['Measured Error'] = errors
host_tbl['Units'] = units

In [92]:
host_tbl

               Quantity Measured Value Measured Error Units
0          Stellar Mass          132.3           50.6   mag
1  Absolute r-band mag.         -20.81           0.05   mag

In [93]:
host_tbl.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Quantity</th>\n      <th>Measured Value</th>\n      <th>Measured Error</th>\n      <th>Units</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Stellar Mass</td>\n      <td>132.3</td>\n      <td>50.6</td>\n      <td>mag</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Absolute r-band mag.</td>\n      <td>-20.81</td>\n      <td>0.05</td>\n      <td>mag</td>\n    </tr>\n  </tbody>\n</table>'